version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: probot
    versions:
    - 11.0.5
    - 11.0.6
    - 11.2.1
    - 11.2.2
    - 11.2.3
  - dependency-name: vercel
    versions:
    - 21.2.1
    - 21.2.2
    - 21.2.3
    - 21.3.0
    - 21.3.1
    - 21.3.2
    - 22.0.0
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.0
    - 17.4.1
  rebase-strategy: disabled
