name: Build and test
on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn test
      - run: yarn build
      # - uses: ./
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
